-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 12:46:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema emple_dep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emple_dep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emple_dep` ;
USE `emple_dep` ;

-- -----------------------------------------------------
-- Table `emple_dep`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emple_dep`.`departamentos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emple_dep`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emple_dep`.`empleados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `legajo` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_incorporacion` DATE NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `sueldo` FLOAT NOT NULL,
  `departamento_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `legajo_UNIQUE` (`legajo` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `departamento_id_idx` (`departamento_id` ASC) VISIBLE,
  CONSTRAINT `departamento_id`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `emple_dep`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
