-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 11:42:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bootcamp_db_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bootcamp_db_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bootcamp_db_1` DEFAULT CHARACTER SET utf8 ;
USE `bootcamp_db_1` ;

-- -----------------------------------------------------
-- Table `bootcamp_db_1`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_db_1`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_db_1`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_db_1`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `legajo` VARCHAR(45) NULL,
  `dni` INT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `birthdate` DATETIME NULL,
  `incorporation` DATETIME NULL,
  `position` VARCHAR(45) NULL,
  `net_income` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_departments_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_departments`
    FOREIGN KEY (`department_id`)
    REFERENCES `bootcamp_db_1`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
