-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 12:52:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema emple_dep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emple_dep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emple_dep`;
USE `emple_dep` ;

-- -----------------------------------------------------
-- Table `emple_dep`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emple_dep`.`Departamentos` (
  `idDepartamentos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emple_dep`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emple_dep`.`Empleados` (
  `Nª legajo` INT NOT NULL AUTO_INCREMENT,
  `Dni` INT NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha Nac` DATETIME NOT NULL,
  `Fecha Inc` DATETIME NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Sueldo Neto` INT NOT NULL,
  `Departamentos_idDepartamentos` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `Nª legajo_UNIQUE` (`Nª legajo` ASC) VISIBLE,
  UNIQUE INDEX `Dni_UNIQUE` (`Dni` ASC) VISIBLE,
  PRIMARY KEY (`Nª legajo`),
  INDEX `fk_Empleados_Departamentos_idx` (`Departamentos_idDepartamentos` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Departamentos`
    FOREIGN KEY (`Departamentos_idDepartamentos`)
    REFERENCES `emple_dep`.`Departamentos` (`idDepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
