definitions:
  handler.request:
    properties:
      active:
        type: boolean
      age:
        type: integer
      created:
        type: string
      email:
        type: string
      height:
        type: number
      last_name:
        type: string
      name:
        type: string
    type: object
  web.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    email: federico.archuby@mercadolibre.com
    name: Archuby Federico
  description: This API Handle MELI USers
  title: MELI Bootcamp API Documentation
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: get users
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: List users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: create user
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: The user data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Create user
      tags:
      - Users
  /users/{od}:
    post:
      consumes:
      - application/json
      description: create user
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: The user data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      - description: The user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Create user
      tags:
      - Users
swagger: "2.0"
